services:
  - type: web
    name: studyguide
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # This will be set manually in Render dashboard
      - key: PORT
        value: "5000" 